[toolchain]
# Must be in sync with .github/actions/setup/action.yml rust-version
# default.
channel = "1.92.0"
targets = [
    "armv7-linux-androideabi",
    "aarch64-linux-android",
    "i686-linux-android",
    "x86_64-linux-android",
]
